Ref T11807#OCID 331## Petition: do not make classes frozen
There was an issue with previous commit which caused:

```
Traceback (most recent call last):
  File "${DIST_PACKAGES}/orcha/__init__.py", line 25, in <module>
    from .interfaces import *
  File "${DIST_PACKAGES}/orcha/interfaces/__init__.py", line 24, in <module>
    from .petition import (
  File "${DIST_PACKAGES}/orcha/interfaces/petition.py", line 208, in <module>
    class EmptyPetition(Petition):
  File "/usr/lib/python3.7/dataclasses.py", line 983, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.7/dataclasses.py", line 868, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

So then, child classes were updated so they are mutable